/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestellungRouteImport } from './routes/bestellung'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as OeffnungszeitenRouteImport } from './routes/oeffnungszeiten'
import { Route as SpeisekarteRouteImport } from './routes/speisekarte'
import { Route as StandortRouteImport } from './routes/standort'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungRoute = BestellungRouteImport.update({
  id: '/bestellung',
  path: '/bestellung',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const OeffnungszeitenRoute = OeffnungszeitenRouteImport.update({
  id: '/oeffnungszeiten',
  path: '/oeffnungszeiten',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeisekarteRoute = SpeisekarteRouteImport.update({
  id: '/speisekarte',
  path: '/speisekarte',
  getParentRoute: () => rootRouteImport,
} as any)
const StandortRoute = StandortRouteImport.update({
  id: '/standort',
  path: '/standort',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestellung': typeof BestellungRoute
  '/checkout': typeof CheckoutRoute
  '/oeffnungszeiten': typeof OeffnungszeitenRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/standort': typeof StandortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bestellung': typeof BestellungRoute
  '/checkout': typeof CheckoutRoute
  '/oeffnungszeiten': typeof OeffnungszeitenRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/standort': typeof StandortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestellung': typeof BestellungRoute
  '/checkout': typeof CheckoutRoute
  '/oeffnungszeiten': typeof OeffnungszeitenRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/standort': typeof StandortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestellung'
    | '/checkout'
    | '/oeffnungszeiten'
    | '/speisekarte'
    | '/standort'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bestellung'
    | '/checkout'
    | '/oeffnungszeiten'
    | '/speisekarte'
    | '/standort'
  id:
    | '__root__'
    | '/'
    | '/bestellung'
    | '/checkout'
    | '/oeffnungszeiten'
    | '/speisekarte'
    | '/standort'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestellungRoute: typeof BestellungRoute
  CheckoutRoute: typeof CheckoutRoute
  OeffnungszeitenRoute: typeof OeffnungszeitenRoute
  SpeisekarteRoute: typeof SpeisekarteRoute
  StandortRoute: typeof StandortRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellung': {
      id: '/bestellung'
      path: '/bestellung'
      fullPath: '/bestellung'
      preLoaderRoute: typeof BestellungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oeffnungszeiten': {
      id: '/oeffnungszeiten'
      path: '/oeffnungszeiten'
      fullPath: '/oeffnungszeiten'
      preLoaderRoute: typeof OeffnungszeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speisekarte': {
      id: '/speisekarte'
      path: '/speisekarte'
      fullPath: '/speisekarte'
      preLoaderRoute: typeof SpeisekarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standort': {
      id: '/standort'
      path: '/standort'
      fullPath: '/standort'
      preLoaderRoute: typeof StandortRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestellungRoute: BestellungRoute,
  CheckoutRoute: CheckoutRoute,
  OeffnungszeitenRoute: OeffnungszeitenRoute,
  SpeisekarteRoute: SpeisekarteRoute,
  StandortRoute: StandortRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
