/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as BestellungRouteImport } from './routes/bestellung'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as OeffnungszeitenRouteImport } from './routes/oeffnungszeiten'
import { Route as SpeisekarteRouteImport } from './routes/speisekarte'
import { Route as StandortRouteImport } from './routes/standort'
import { Route as ApiPublicOrderPushRouteImport } from './routes/api/public/order-push'
import { Route as ApiPublicPaymentsConfigRouteImport } from './routes/api/public/payments/config'
import { Route as ApiPublicPaymentsCreateIntentRouteImport } from './routes/api/public/payments/create-intent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const BestellungRoute = BestellungRouteImport.update({
  id: '/bestellung',
  path: '/bestellung',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const OeffnungszeitenRoute = OeffnungszeitenRouteImport.update({
  id: '/oeffnungszeiten',
  path: '/oeffnungszeiten',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeisekarteRoute = SpeisekarteRouteImport.update({
  id: '/speisekarte',
  path: '/speisekarte',
  getParentRoute: () => rootRouteImport,
} as any)
const StandortRoute = StandortRouteImport.update({
  id: '/standort',
  path: '/standort',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderPushRoute = ApiPublicOrderPushRouteImport.update({
  id: '/api/public/order-push',
  path: '/api/public/order-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsConfigRoute = ApiPublicPaymentsConfigRouteImport.update({
  id: '/api/public/payments/config',
  path: '/api/public/payments/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsCreateIntentRoute =
  ApiPublicPaymentsCreateIntentRouteImport.update({
    id: '/api/public/payments/create-intent',
    path: '/api/public/payments/create-intent',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agb': typeof AgbRoute
  '/bestellung': typeof BestellungRoute
  '/checkout': typeof CheckoutRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/oeffnungszeiten': typeof OeffnungszeitenRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/standort': typeof StandortRoute
  '/api/public/order-push': typeof ApiPublicOrderPushRoute
  '/api/public/payments/config': typeof ApiPublicPaymentsConfigRoute
  '/api/public/payments/create-intent': typeof ApiPublicPaymentsCreateIntentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agb': typeof AgbRoute
  '/bestellung': typeof BestellungRoute
  '/checkout': typeof CheckoutRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/oeffnungszeiten': typeof OeffnungszeitenRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/standort': typeof StandortRoute
  '/api/public/order-push': typeof ApiPublicOrderPushRoute
  '/api/public/payments/config': typeof ApiPublicPaymentsConfigRoute
  '/api/public/payments/create-intent': typeof ApiPublicPaymentsCreateIntentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agb': typeof AgbRoute
  '/bestellung': typeof BestellungRoute
  '/checkout': typeof CheckoutRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/oeffnungszeiten': typeof OeffnungszeitenRoute
  '/speisekarte': typeof SpeisekarteRoute
  '/standort': typeof StandortRoute
  '/api/public/order-push': typeof ApiPublicOrderPushRoute
  '/api/public/payments/config': typeof ApiPublicPaymentsConfigRoute
  '/api/public/payments/create-intent': typeof ApiPublicPaymentsCreateIntentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agb'
    | '/bestellung'
    | '/checkout'
    | '/datenschutz'
    | '/impressum'
    | '/oeffnungszeiten'
    | '/speisekarte'
    | '/standort'
    | '/api/public/order-push'
    | '/api/public/payments/config'
    | '/api/public/payments/create-intent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agb'
    | '/bestellung'
    | '/checkout'
    | '/datenschutz'
    | '/impressum'
    | '/oeffnungszeiten'
    | '/speisekarte'
    | '/standort'
    | '/api/public/order-push'
    | '/api/public/payments/config'
    | '/api/public/payments/create-intent'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agb'
    | '/bestellung'
    | '/checkout'
    | '/datenschutz'
    | '/impressum'
    | '/oeffnungszeiten'
    | '/speisekarte'
    | '/standort'
    | '/api/public/order-push'
    | '/api/public/payments/config'
    | '/api/public/payments/create-intent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgbRoute: typeof AgbRoute
  BestellungRoute: typeof BestellungRoute
  CheckoutRoute: typeof CheckoutRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  OeffnungszeitenRoute: typeof OeffnungszeitenRoute
  SpeisekarteRoute: typeof SpeisekarteRoute
  StandortRoute: typeof StandortRoute
  ApiPublicOrderPushRoute: typeof ApiPublicOrderPushRoute
  ApiPublicPaymentsConfigRoute: typeof ApiPublicPaymentsConfigRoute
  ApiPublicPaymentsCreateIntentRoute: typeof ApiPublicPaymentsCreateIntentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestellung': {
      id: '/bestellung'
      path: '/bestellung'
      fullPath: '/bestellung'
      preLoaderRoute: typeof BestellungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oeffnungszeiten': {
      id: '/oeffnungszeiten'
      path: '/oeffnungszeiten'
      fullPath: '/oeffnungszeiten'
      preLoaderRoute: typeof OeffnungszeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speisekarte': {
      id: '/speisekarte'
      path: '/speisekarte'
      fullPath: '/speisekarte'
      preLoaderRoute: typeof SpeisekarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standort': {
      id: '/standort'
      path: '/standort'
      fullPath: '/standort'
      preLoaderRoute: typeof StandortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-push': {
      id: '/api/public/order-push'
      path: '/api/public/order-push'
      fullPath: '/api/public/order-push'
      preLoaderRoute: typeof ApiPublicOrderPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/config': {
      id: '/api/public/payments/config'
      path: '/api/public/payments/config'
      fullPath: '/api/public/payments/config'
      preLoaderRoute: typeof ApiPublicPaymentsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/create-intent': {
      id: '/api/public/payments/create-intent'
      path: '/api/public/payments/create-intent'
      fullPath: '/api/public/payments/create-intent'
      preLoaderRoute: typeof ApiPublicPaymentsCreateIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgbRoute: AgbRoute,
  BestellungRoute: BestellungRoute,
  CheckoutRoute: CheckoutRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  OeffnungszeitenRoute: OeffnungszeitenRoute,
  SpeisekarteRoute: SpeisekarteRoute,
  StandortRoute: StandortRoute,
  ApiPublicOrderPushRoute: ApiPublicOrderPushRoute,
  ApiPublicPaymentsConfigRoute: ApiPublicPaymentsConfigRoute,
  ApiPublicPaymentsCreateIntentRoute: ApiPublicPaymentsCreateIntentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
